In [1]:
import numpy as np

In [26]:
a = np.array([1,2,3], dtype= 'int32')
print (a)

[1 2 3]


In [27]:
b = np. array ([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print (b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [33]:
 #get dimension for a 
a.ndim

1

In [32]:
#get shape for a
a.shape

(3,)

In [31]:
#get shape for b 
b.shape
#it's a 2x3 matrix

(2, 3)

In [29]:
#get type 
a.dtype

dtype('int32')

In [28]:
#get size 
b.itemsize 

8

In [30]:
#get total size 
a.size*a.itemsize

12

In [34]:
a = np. array ([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print (a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [37]:
#get a specific element [r,c]
a[1,5]
#remember that python indexing starts at zero 

13

In [38]:
#get specific row 
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [39]:
#get a specific column 
a[:,2]

array([ 3, 10])

In [40]:
  #getting a little more fancy [startindex: end index:stepsize]
a[0,1:6:2]

array([2, 4, 6])

In [41]:
a[1,5] = 20
#the number thirteen, previously in the spot [1,5] has been replaced with a 20
print (a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [44]:
b = np.array ([[[1,2],[3,4]],[[5,6],[7,8]]])
print (b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [45]:
#INITIALIZING DIFFERENT TYPES OF ARRAYS 

#All 0s matrix 

np.zeros((2,3,3,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [46]:
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [48]:
#any other number 
np.full ((2,2),99, dtype = 'float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [50]:
#any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [57]:
#random decimal numbers 
np.random.rand (4,2,3)

array([[[0.42574105, 0.52755887, 0.75459209],
        [0.79074789, 0.39348367, 0.18742328]],

       [[0.48358308, 0.52958727, 0.60772667],
        [0.52528399, 0.20388085, 0.52986644]],

       [[0.79327538, 0.8214316 , 0.12879846],
        [0.67715669, 0.55087325, 0.87038643]],

       [[0.41683462, 0.61366781, 0.68855456],
        [0.93200249, 0.26730415, 0.46825838]]])

In [75]:
#random integer values 
np.random.randint(15, size = (3,3))

array([[13,  9, 10],
       [ 5, 14,  0],
       [ 3, 12, 13]])

In [78]:
np.identity(3)
#the identity matrix 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [83]:
arr = np.array ([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print (r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [91]:
exampl = np.ones((5,5), dtype = 'int32')
exampl[2,2]=9
exampl[1,1:4]=0
exampl[3,1:4] = 0
exampl[2,1] = 0 
exampl[2,3] = 0
print (exampl)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [92]:
#be careful when copying arrays 
a = np.array([1,2,3])
b = a
b[0] =100
print (a)
#this changes a too though!!

[100   2   3]


In [94]:
#proper way to copy arrays 
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print (b)
print (a)

[100   2   3]
[1 2 3]


In [95]:
#MATHEMATICS 
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [96]:
a+2 

array([3, 4, 5, 6])

In [97]:
a-2

array([-1,  0,  1,  2])

In [98]:
a*2

array([2, 4, 6, 8])

In [99]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [100]:
b = np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [101]:
a**2

array([ 1,  4,  9, 16])

In [106]:
 #take the sine and cosine of all of the values 
print (np.sin(a))
print (np.cos(a))


[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


In [107]:
##LINEAR ALGEBRA

In [116]:
a = np.full((2,3),1)
print (a)

b = np.full ((3,2),2)
print(b)

print (np.matmul(a,b)) #matrix multiplication

[[1 1 1]
 [1 1 1]]
[[2 2]
 [2 2]
 [2 2]]
[[6 6]
 [6 6]]


In [118]:
#find the determinant 
c = np.identity (3)
np.linalg.det(c)

1.0

In [119]:
#Reference docs 

#determinant 
#trace 
#singular vector decomposition 
#eigenvalues 
#matrix norm 
#inverse 
#etc 

In [121]:
#Statistics 

stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [123]:
np.min(stats,axis=0)

array([1, 2, 3])

In [124]:
np.min(stats)

1

In [125]:
np.max(stats)

6

In [126]:
np.sum(stats, axis=0)

array([5, 7, 9])

In [127]:
#Reorganizing Arrays 

In [131]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print (before)
after = before.reshape((8,1))
print (after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [133]:
#Vertically stacking vectors 
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [134]:
#Horizontal stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [135]:
#MISCELLANEOUS 

In [136]:
#Load data from file 
np.genfromtxt('data.txt',delimiter = ',')
filedata.astype('int32')

FileNotFoundError: data.txt not found.

In [137]:
##Boolean Masking and Advanced Indexing 
filedata > 50 #shows where the values greater than 50 are in the array
filedata[filedata>50]#grabs only the values that are greater than 50 

NameError: name 'filedata' is not defined

In [138]:
##you can index with a list in mumpy 
a= np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])